#!/bin/sh

set -eu

. "$(dirname "$0")/dunst-registry"

export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus

path=$1
d="dunstify -r $INCRON_PASSWORDS -i /usr/share/keepassxc/icons/application/256x256/apps/keepassxc.png"

$d 'syncing pass to google drive' \
    && rclone sync $path barakus:passwords/ --retries 20 \
    && $d -t 900 "synced pass files to google drive" \
    || $d -u 2 -t 1300 "error syncing"
