#!/usr/bin/env sh

umask 0077

PATH="$HOME/.local/bin:$PATH"

CONTEXT=$(mise exec -- yq -r '.["current-context"]' ~/.kube/config 2>/dev/null || echo empty)

# shellcheck disable=SC2016
KUBECONFIG="$(find ~/.kube/clusters -type f\
                | grep -v lock \
                | xargs echo \
                | sed 's/ /:/g')" \
  mise exec -- kubectl \
  config view --flatten \
  | mise exec -- yq -Y --arg context "$CONTEXT" '.["current-context"]=$context' \
  > ~/.kube/config
