#!/bin/sh

set -eu

. "$(dirname "$0")/dunst-registry"

for idx in $(pactl -f json list sinks | jq '.[] | select(.description|test("^(monitors|.*Renoir).*")) .index')
do

    pactl set-sink-mute "$idx" toggle

done

if [ $(pactl -f json list sinks | jq '.[] | select(.description|test("^monitors.*")) .mute') = 'true' ]
then
    title='🔈'
    message='muted'
else
    title='🔊'
    message='unmuted'
fi

dunstify -i display -r $TOGGLE_MUTE -t 800 "$title" $message
