#!/bin/sh

set -eu

. "$(dirname "$0")/dunst-registry"

pactl set-sink-mute @DEFAULT_SINK@ toggle

if [ "$(pactl -f json list sinks | jq '.[] | select(.state=="RUNNING") .mute')" = true ]
then
    title='🔈'
    message='muted'
else
    title='🔊'
    message='unmuted'
fi

dunstify -i display -r $TOGGLE_MUTE -t 800 "$title" $message
