#!/bin/sh

set -eu

. "$(dirname "$0")/dunst-registry"

current_sink="$(pactl info | grep 'Default Sink' | cut -d':' -f 2 | xargs)"

new_sink="$(pactl -f json list sinks | jq -r '.[] .name' | grep -v "$current_sink" | grep -v pro-output)"

pactl set-default-sink "$new_sink"

description="$(pactl -f json list sinks  | jq -r ".[] | select(.name==\"$new_sink\") .description")"
dunstify -r $SWITCH_SINK -t 800 "audio output" "\noutput is now $description"
