#!/bin/bash

set -eu

. "$(dirname "$0")/dunst-registry"

current_sink=$(pactl get-default-sink)
new_sink="$(pactl -f json list sinks \
		  | jq -r '.[] | "\(.state) \(.name)"' \
		  | { a="$(</dev/stdin)";  echo "$a"; echo "$a"; } \
		  | grep -A1 "$current_sink" --no-group-separator \
		  | grep -v "$current_sink" \
		  | uniq \
		  | awk '{print $2}')"

pactl set-default-sink "$new_sink"

description="$(pactl -f json list sinks  | jq -r ".[] | select(.name==\"$new_sink\") .description")"
killall -USR2 i3status-rs
dunstify -r $SWITCH_SINK -t 800 "audio output" "\noutput is now $description"
